### ISSUE TITLE
changing ~/.ssh/config is a bad idea, sometimes this isn't managed manually

### ISSUE THREAD

**Issue by cnf** [KryptCo/homebrew-tap#3]
I use [assh](https://github.com/moul/advanced-ssh-config) which manages my ~/.ssh/config. There are other situations where the ssh_config isn't manually managed.

Editing the ssh_config without user consent at best doesn't work, and at worse breaks the users ssh setup.

Please don't do this... echo what to do or make a command to do it, but don't do this without asking for it.

**Comment by jbgosselin** [comment]
I totally agree, I love your product but I removed it just because I don't want re-do my ssh config every-time it is updated.

**Comment by halostatue** [comment]
This should be fixable with a post-message and/or a “build-time” option (`--no-ssh-config`) so that those of us who manage your SSH configurations can force reconfiguration based on the new settings (I have things set up to handle this correctly).

**Comment by kcking** [comment]
Sorry for the incompatibility with assh. As a stopgap fix, I added a `--without-ssh-config` option which will not run any commands to modify ~/.ssh/config and prints what should be added there in the caveats.

We might move ssh_config logic to `kr pair` and prompt the user then

**Comment by kcking** [comment]
Our latest update moves SSH configuration to the `kr pair` stage instead of installation time. This solves the issue of SSH not being configured for other usernames on the computer. We added an env var to prevent `kr` from touching your ssh config, `export KR_SKIP_SSH_CONFIG=1`. Note that the config file is always backed up in the same directory before we modify it.
